### ISSUE TITLE
cannot get flame as package

### ISSUE THREAD

**Issue by matejthetree** [luanpotter/flame-example#1]
Hello,

when I try to do your example I get this error

https://gist.github.com/anonymous/7f952cf013ab6d9729f4337b47342c00

Any help :)

**Comment by luanpotter** [comment]
Hi!

Could you provide your full pubspec.yaml file?

I just ran the code in this repo and `flutter pub get` works as expected. In what command exactly are you getting the error described?

Some of my theories:

* You should always run `flutter pub get`, and not `pub get`, as it's a flutter package
* Make sure your `pubspec.yaml` is indented correctly
* Maybe your project is called `flame`? I don't know if that'd be a problem, but by your error it seems that that's the reason it's complaining (a dependency, flame, with the same name as your app (flame))

**Comment by ramaranjandey** [comment]
Could not find method google() for arguments [] on repository container.
I am getting this issue when i am installing flame game engine

**Comment by luanpotter** [comment]
Please try to run this repository as is, pub get and then run it should work. Either master with an older version of flame or the 0.8.x branch with a more updated one. Otherwise, please provide the full error log and pubspec configuration.

**Comment by ramaranjandey** [comment]
```name: flame_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.9.5
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/crate.png
   - assets/images/explosion.png
   - assets/audio/explosion.mp3
   - assets/audio/miss.mp3
   - assets/audio/music.ogg

  fonts:
   - family: Halo
     fonts:
      - asset: assets/fonts/halo.ttf```

**Comment by ramaranjandey** [comment]
```
name: flame_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.9.5
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/crate.png
   - assets/images/explosion.png
   - assets/audio/explosion.mp3
   - assets/audio/miss.mp3
   - assets/audio/music.ogg

  fonts:
   - family: Halo
     fonts:
      - asset: assets/fonts/halo.ttf
```
